drop table if exists Orders cascade;

create table if not exists Orders
(
    id        bigint generated by default as identity not null,
    driver_id bigint                                  not null unique,
    car_id    bigint                                  not null unique,
    client_id bigint                                  not null,
    "from"    varchar                                 not null,
    "to"      varchar                                 not null,
    constraint PK_Order primary key (ID)
);
