CREATE TABLE driver
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(20)                             NOT NULL,
    last_name     VARCHAR(20)                             NOT NULL,
    father_name   VARCHAR(20),
    date_of_birth date                                    NOT NULL,
    age           INTEGER,
    email         VARCHAR(255)                            NOT NULL,
    address       VARCHAR(100)                            NOT NULL,
    salary        INTEGER                                 NOT NULL,
    CONSTRAINT pk_driver PRIMARY KEY (id)
);

ALTER TABLE driver
    ADD CONSTRAINT uc_driver_address UNIQUE (address);

ALTER TABLE driver
    ADD CONSTRAINT uc_driver_email UNIQUE (email);